@api_url = http://localhost:5192

###

POST {{api_url}}/v1/token
Accept: application/json
Content-Type: application/json

{
  "email": "salmeidabatista@gmail.com",
  "password": "Test@124"
}

> {%
    console.log("token: " + response.body.token);
    client.global.set("auth_token", response.body.token);
  
%}

###

POST {{api_url}}/v1/users/
Accept: application/json
Content-Type: application/json

{
  "name": "test w",
  "email": "test1@gmail.com",
  "password": "test@123"
}

###

POST {{api_url}}/v1/users/worker
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "test 123",
  "email": "test1@worker.com",
  "password": "test@123"
}

###


GET {{api_url}}/v1/users/me
Accept: application/json
Authorization: Bearer {{auth_token}}

###

PATCH {{api_url}}/v1/users/change-password
Accept: application/json
Content-Type: application/json

{
  "email": "salmeidabatista@gmail.com",
  "currentPassword": "Test@123",
  "newPassword": "Test@124"
}
